url: "https://Yujia-Zhou-2006.github.io"
baseurl: ""

title: "Yujia-site"
tagline: "Hello, I am Yujia Zhou"
theme:

social_order:
  - github
  - email
  - wechat
  - instagram
  - red
  - itch
  - pixilart

social:
  github: "https://github.com/Yujia-Zhou-2006"
  email: "zhouyujia-2006@outlook.com"
  wechat_id: "Creeper3445"
  instagram: "https://www.instagram.com/gz_scalemodel/"
  red: "https://www.xiaohongshu.com/user/profile/642e3d610000000012010db4"
  itch: "https://georgezhou.itch.io/"
  pixilart: "https://www.pixilart.com/georgezhou"

pinned_projects:
  - bf-109-f4-models
  - p51-c-models
  - night-impression-pixel
  - nonlinear-sprite-motion-pico8

collections:
  projects:
    output: true
    permalink: /projects/:slug/

permalink: /blog/:year/:month/:day/:title/

profile:
  name: "Yujia Zhou"
  birthday: "2006/09/04"
  location: "USA PA Harrisburg "
  school: "PSU Harrisburg"
  hobbies: "Modeling,Pixel art"
  bio: "A passionate developer and digital artist, exploring the intersection of technology and creativity."
